### ISSUE TITLE
Potential Crash

### ISSUE THREAD

**Issue by GHSpencerA** [corbinstreehouse/Mach-4-Avid-CNC-Customizations#1]
If a tool change is called while the spindle is close to the tool rack, it has the potential to crash into other tool holders after picking up the new tool. Suggest moving back across the rack after a tool is picked up.

**Comment by corbinstreehouse** [comment]
Thanks! This is a good idea, and should be an easy fix. I'll get to it soon.

**Comment by corbinstreehouse** [comment]
Okay; easy fix! Pushing a new release right now.
